name: Deploy to AWS

on:
  push:
    branches:
      - main # mainブランチへのプッシュでprod環境にデプロイ
      - develop # developブランチへのプッシュでdev環境にデプロイ

env:
  AWS_REGION: ap-northeast-1 # デプロイ先のAWSリージョン

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # OIDC (OpenID Connect) を使用する場合に必要。AWSアクションでは推奨される設定です。
      contents: read  # actions/checkout@v4 など、リポジリポジトリの内容を読み取るアクションに必要です。
    # 環境変数を動的に設定
    env:
      ENV_NAME: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Node.jsのバージョン

      - name: Install Lambda dependencies
        run: npm install
        working-directory: lambda

      - name: Install CDK dependencies
        run: npm install
        working-directory: infra # infraディレクトリで実行

      - name: Deploy CDK Stack
        run: npx cdk deploy -c env=${{ env.ENV_NAME }} --require-approval never --outputs-file cdk-outputs.json
        working-directory: infra
        id: cdk_deploy # ステップにIDを付与して出力を参照できるようにする

      - name: Debug CDK Outputs
        run: |
          echo "=== CDK Outputs Debug ==="
          if [ -f cdk-outputs.json ]; then
            echo "cdk-outputs.json exists"
            cat cdk-outputs.json
            echo ""
            echo "Pretty printed:"
            jq '.' cdk-outputs.json
          else
            echo "cdk-outputs.json not found!"
            ls -la
          fi
        working-directory: infra

      - name: Extract CDK Outputs
        id: get_outputs
        run: |
          # まず、アウトプットファイルの内容を確認
          if [ ! -f cdk-outputs.json ]; then
            echo "Error: cdk-outputs.json not found"
            exit 1
          fi
          
          # スタック名のパターンを複数試してみる
          POSSIBLE_STACK_NAMES=(
            "InfraStack-${{ env.ENV_NAME }}"
            "InfraStack${{ env.ENV_NAME }}" 
            "infra-stack-${{ env.ENV_NAME }}"
            "InfraStack"
          )
          
          # 実際のスタック名を見つける
          ACTUAL_STACK_NAME=""
          for stack_name in "${POSSIBLE_STACK_NAMES[@]}"; do
            if jq -e --arg stack "$stack_name" 'has($stack)' cdk-outputs.json > /dev/null 2>&1; then
              ACTUAL_STACK_NAME="$stack_name"
              echo "Found stack: $ACTUAL_STACK_NAME"
              break
            fi
          done
          
          if [ -z "$ACTUAL_STACK_NAME" ]; then
            echo "Error: Could not find matching stack name"
            echo "Available stacks:"
            jq -r 'keys[]' cdk-outputs.json
            exit 1
          fi
          
          # 可能なキー名のパターンを試す
          POSSIBLE_API_KEYS=(
            "ApiEndpoint-${{ env.ENV_NAME }}"
            "ApiEndpoint${{ env.ENV_NAME }}"
            "apiEndpoint"
            "ApiEndpoint"
            "API_ENDPOINT"
          )
          
          POSSIBLE_BUCKET_KEYS=(
            "FrontendBucketName-${{ env.ENV_NAME }}"
            "FrontendBucketName${{ env.ENV_NAME }}"
            "frontendBucketName"
            "FrontendBucketName"
            "FRONTEND_BUCKET_NAME"
          )
          
          POSSIBLE_CLOUDFRONT_KEYS=(
            "CloudFrontDistributionId-${{ env.ENV_NAME }}"
            "CloudFrontDistributionId${{ env.ENV_NAME }}"
            "cloudFrontDistributionId"
            "CloudFrontDistributionId"
            "CLOUDFRONT_DISTRIBUTION_ID"
          )
          
          # API エンドポイントを取得
          API_ENDPOINT=""
          for key in "${POSSIBLE_API_KEYS[@]}"; do
            value=$(jq -r --arg stack "$ACTUAL_STACK_NAME" --arg key "$key" '.[$stack][$key] // empty' cdk-outputs.json)
            if [ ! -z "$value" ] && [ "$value" != "null" ]; then
              API_ENDPOINT="$value"
              echo "Found API endpoint with key: $key"
              break
            fi
          done
          
          # バケット名を取得
          FRONTEND_BUCKET_NAME=""
          for key in "${POSSIBLE_BUCKET_KEYS[@]}"; do
            value=$(jq -r --arg stack "$ACTUAL_STACK_NAME" --arg key "$key" '.[$stack][$key] // empty' cdk-outputs.json)
            if [ ! -z "$value" ] && [ "$value" != "null" ]; then
              FRONTEND_BUCKET_NAME="$value"
              echo "Found bucket name with key: $key"
              break
            fi
          done
          
          # CloudFront ID を取得
          CLOUDFRONT_DISTRIBUTION_ID=""
          for key in "${POSSIBLE_CLOUDFRONT_KEYS[@]}"; do
            value=$(jq -r --arg stack "$ACTUAL_STACK_NAME" --arg key "$key" '.[$stack][$key] // empty' cdk-outputs.json)
            if [ ! -z "$value" ] && [ "$value" != "null" ]; then
              CLOUDFRONT_DISTRIBUTION_ID="$value"
              echo "Found CloudFront ID with key: $key"
              break
            fi
          done
          
          # 結果を出力
          echo "API_ENDPOINT=$API_ENDPOINT" >> $GITHUB_OUTPUT
          echo "FRONTEND_BUCKET_NAME=$FRONTEND_BUCKET_NAME" >> $GITHUB_OUTPUT
          echo "CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID" >> $GITHUB_OUTPUT
          
          # デバッグ用に値を表示
          echo "Extracted values:"
          echo "  API_ENDPOINT: $API_ENDPOINT"
          echo "  FRONTEND_BUCKET_NAME: $FRONTEND_BUCKET_NAME"
          echo "  CLOUDFRONT_DISTRIBUTION_ID: $CLOUDFRONT_DISTRIBUTION_ID"
          
          # 必須の値が取得できているかチェック
          if [ -z "$FRONTEND_BUCKET_NAME" ] || [ "$FRONTEND_BUCKET_NAME" = "null" ]; then
            echo "Error: Frontend bucket name not found"
            exit 1
          fi
          
          if [ -z "$CLOUDFRONT_DISTRIBUTION_ID" ] || [ "$CLOUDFRONT_DISTRIBUTION_ID" = "null" ]; then
            echo "Error: CloudFront distribution ID not found"
            exit 1
          fi
        working-directory: infra

      - name: Install Frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build Frontend
        run: |
          echo "--- Before npm run build ---"
          ls -la
          VITE_API_ENDPOINT=${{ steps.get_outputs.outputs.API_ENDPOINT }} npm run build
          echo "--- After npm run build ---"
          ls -la
          if [ -d dist ]; then
            ls -la dist
          else
            echo "dist directory not found!"
            exit 1
          fi
        working-directory: frontend

      - name: Deploy Frontend to S3
        run: |
          echo "Deploying to bucket: ${{ steps.get_outputs.outputs.FRONTEND_BUCKET_NAME }}"
          echo "CloudFront distribution: ${{ steps.get_outputs.outputs.CLOUDFRONT_DISTRIBUTION_ID }}"
          
          if [ ! -d dist ]; then
            echo "Error: dist directory not found"
            exit 1
          fi
          
          aws s3 sync dist s3://${{ steps.get_outputs.outputs.FRONTEND_BUCKET_NAME }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ steps.get_outputs.outputs.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        working-directory: frontend