name: Seed Database

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to seed the database for'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: 'dev'

env:
  AWS_REGION: ap-northeast-1

jobs:
  seed-database:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install script dependencies
        run: npm install
        working-directory: scripts

      - name: Run seeding script
        run: ENV_NAME=${{ github.event.inputs.environment }} npm run seed
        working-directory: scripts
